### ISSUE TITLE
12 gen processor failed test

### ISSUE THREAD

**Issue by ToddAndMargo** [rcmaehl/WhyNotWin11#690]
WhyNotWin11-2.4.3.21.exe

A brand new Lenovo 11TT000HUS:
https://www.lenovo.com/us/en/p/desktops/thinkcentre/m-series-sff/thinkcentre-m90s-gen-3-(intel)/11tt000hus
with W11-Pro-21H2 pre-installed.  And Why Not Win 11 failed it:

![R D WhyNot11](https://user-images.githubusercontent.com/843205/177892437-e7b17193-6205-4278-8d9e-82109ba4000b.png)

it says the processor is a "12th Gen Intel(R) Core(TM) i5-12500", which sound like it should pass.  This is probably a bug in Why Not Win 11

**Comment by micwoj92** [comment]
Please check with latest version

**Comment by ToddAndMargo** [comment]
WhyNotWin11-2.5.0.1.exe
No symptom change
![R D WhyNot11 2](https://user-images.githubusercontent.com/843205/178058689-17620f58-6394-4445-9b7a-aaba0e53eb1b.png)

**Comment by rcmaehl** [comment]
Will get that updated

**Comment by WilloIzCitron** [comment]
probably yes but manual update not automatic

**Comment by ToddAndMargo** [comment]
Another new laptop running Windows 11 failed as well:
![DeDe WhyNotWin11](https://user-images.githubusercontent.com/843205/186954003-45699064-1ac1-4c7c-b4fa-9adc5a4d8447.png)

**Comment by rcmaehl** [comment]
> Another new laptop running Windows 11 failed as well: ![DeDe WhyNotWin11](https://user-images.githubusercontent.com/843205/186954003-45699064-1ac1-4c7c-b4fa-9adc5a4d8447.png)

i5-1235U? or what is your actual CPU if not?

**Comment by rcmaehl** [comment]
> WhyNotWin11-2.5.0.1.exe No symptom change ![R D WhyNot11 2](https://user-images.githubusercontent.com/843205/178058689-17620f58-6394-4445-9b7a-aaba0e53eb1b.png)

Fixed in 2.5.0.2

**Comment by ToddAndMargo** [comment]
On 8/27/22 09:37, Robert C. Maehl wrote:
>     WhyNotWin11-2.5.0.1.exe No symptom change R D WhyNot11 2
>     <https://user-images.githubusercontent.com/843205/178058689-17620f58-6394-4445-9b7a-aaba0e53eb1b.png>
> 
> Fixed in 2.5.0.2

Any idea when it will hit general release?

**Comment by micwoj92** [comment]
It's released already

**Comment by ToddAndMargo** [comment]
Still not fixed.  :'(

![Tom Laptop WhyNotWin11](https://user-images.githubusercontent.com/843205/192081333-02e38fce-721a-4ecb-9027-6f68ac2750f6.png)
